### ISSUE TITLE
Error in running main.py

### ISSUE THREAD

**Issue by mvanwaveren** [Scientific-Computing-Lab-NRCN/HPCorpus#1]
Hello,

I cloned your repository and executed the Usage steps:

> Update the ENV.json file with your system's path to the HPCorpus directory.
> Run the following command: python main.py

My system path is 

> /home/waveren/HPCorpus

I get the following error message:

> Traceback (most recent call last):
>   File "main.py", line 84, in <module>
>     iterate_jsons('Fortran', vars, is_fortran=True)
>   File "main.py", line 29, in iterate_jsons
>     for json_file in os.listdir(dir_path):
> OSError: [Errno 2] No such file or directory: '/home/waveren/HPCorpus/Fortran'

There is no Fortran directory in the repository. Could you advise me how to proceed ?

Regards,
Matthijs van Waveren

**Comment by mvanwaveren** [comment]
Reminder of this issue. Could you respond?
